version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/intothedata
    environment:
      HUGO_BUILD_DIR: ~/intothedata/public
    steps:
      - run: apk update && apk add git
      - run: apk add rsync
      - checkout
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR --config $HUGO_BUILD_DIR/config.toml
      - run: |
          htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
          --empty-alt-ignore --disable-external
